export const jobTagsArray = [
  "remote",
  "full-time",
  "part-time",
  "contract",
  // "front-end",
  // "back-end",
  // "full-stack",
  // "mobile",
  // "web",
  // "ux",
  // "ui",
  // "javascript",
  // "react",
  // "node",
  // "express",
  // "ruby",
  // "rails",
  // "python",
  // "django",
  // "c++",
  // "c#",
  // "java",
  // "php",
  // "swift",
  // "ios",
  // "android",
  // "aws",
  // "azure",
  // "google",
  // "firebase",
  // "mongodb",
  // "mysql",
  // "postgresql",
  // "sql",
  // "nosql",
];
