export const jobTagsArray = [
  { value: "full-time", label: "Full-time" },
  { value: "part-time", label: "Part-time" },
  { value: "contract", label: "Contract" },
  { value: "front-end", label: "Front End" },
  { value: "back-end", label: "Back End" },
  { value: "full-stack", label: "Full Stack" },
  { value: "android", label: "Android" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "c#", label: "C#" },
  { value: "c++", label: "C++" },
  { value: "crypto", label: "Crypto" },
  { value: "blockchain", label: "Blockchain" },
  { value: "data-science", label: "Data Science" },
  { value: "devops", label: "Devops" },
  { value: "design", label: "Design" },
  { value: "django", label: "Django" },
  { value: "express", label: "Express" },
  { value: "firebase", label: "Firebase" },
  { value: "google", label: "Google" },
  { value: "ios", label: "iOS" },
  { value: "java", label: "Java" },
  { value: "javascript", label: "JavaScript" },
  { value: "mobile", label: "Mobile" },
  { value: "mongodb", label: "MongoDB" },
  { value: "mysql", label: "MySQL" },
  { value: "node", label: "Node.js" },
  { value: "nosql", label: "NoSQL" },
  { value: "nft", label: "NFT" },
  { value: "php", label: "PHP" },
  { value: "postgresql", label: "PostgresSQL" },
  { value: "python", label: "Python" },
  { value: "rails", label: "Rails" },
  { value: "react", label: "React" },
  { value: "ruby", label: "Ruby" },
  { value: "sql", label: "SQL" },
  { value: "swift", label: "Swift" },
  { value: "ui", label: "UI" },
  { value: "ux", label: "UX" },
];
