on: push

jobs:
  linting:
    name: Formatting and Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint --max-warnings 0
